# korail-mobile-api — https://github.com/yakisoba0728/korail-mobile-api
# Copyright (c) 2026 yakisoba0728
# SPDX-License-Identifier: Apache-2.0

"""KORAIL 모바일 앱 API 파이썬 클라이언트의 공개면.

여기서 import 할 수 있는 이름이 이 패키지가 지원하는 전부입니다. ``__all__`` 에
없는 것은 하위 모듈에 있더라도 예고 없이 바뀝니다.

시작점은 둘입니다 — :class:`~korail_mobile_api.client.KorailClient`(모든 호출),
:class:`~korail_mobile_api.config.KorailConfig`(기기 신원과 타임아웃). 대기열은
:class:`~korail_mobile_api.netfunnel.KorailNetFunnelClient` 로 따로 떨어져 있고
기본적으로 꺼져 있습니다.

실패는 :class:`~korail_mobile_api.errors.KorailApiError` 아래로 모이며,
``h_msg_cd`` 를 예외 클래스로 옮기는 규칙은
:func:`~korail_mobile_api.errors.classify_app_error` 하나에 있습니다.
"""

#: 배포된 버전. ``__all__`` 에 넣지 않는 것은 의도다 — 던더는 export 하는 이름
#: 집합이 아니고, ``from korail_mobile_api import *`` 가 이것을 실어 나른 적이
#: 없다. 패키징 메타데이터가 삭제된 지금 이 값이 유일한 버전 선언이다.
__version__ = "1.2.0"

from .client import KorailClient
from .config import KorailConfig, enabled_dynapath_config
from .constants import (
    KORAIL_COMMON_CODE_BOOTSTRAP_CODES,
    KORAIL_DIRECT_ITINERARY_CODE,
    KORAIL_MAX_DISCOUNT_CARD_SECTIONS,
    KORAIL_MAX_JOURNEY_LEGS,
    KORAIL_MAX_PASSENGERS_PER_RESERVATION,
    KORAIL_MERGE_SEAT_FLAGS_BY_CABIN,
    KORAIL_STANDBY_HOLD_MESSAGE_CODE,
    KORAIL_TRANSFER_ITINERARY_CODE,
    KORAIL_USER_AGENT,
    KorailNetFunnelAction,
    KorailReservationJobType,
    KorailSeatClass,
)
from .dynapath import (
    DynapathConfig,
    DynapathTokenSettings,
)
from .errors import (
    KorailApiError,
    KorailAppError,
    KorailAppUpdateRequiredError,
    KorailAuthContinuationRequired,
    KorailAuthError,
    KorailDynaPathError,
    KorailDynaPathRequiredError,
    KorailInvalidRequestError,
    KorailMutationNotAllowedError,
    KorailNetFunnelError,
    KorailNoDirectTrainError,
    KorailNoResultsError,
    KorailNotEntitledError,
    KorailProtocolError,
    KorailQueueRejectedError,
    KorailReservationRefusedError,
    KorailSeatUnavailableError,
    KorailServiceUnavailableError,
    KorailSessionExpiredError,
    KorailSoldOutError,
    KorailTransportError,
    classify_app_error,
)
from .limousine_models import (
    LimousineRecommendedProduct,
    LimousineSchedule,
    LimousineScheduleQuery,
    LimousineScheduleResponse,
    LimousineScheduleViewResponse,
    LimousineScheduleViewTrain,
    LimousineSeat,
    LimousineSeatInventoryQuery,
    LimousineSeatInventoryResponse,
)

# Imported LAST among the package's own modules on purpose. ``live`` sits on
# top of the stack — it imports ``client``, which imports everything else — so
# pulling it in earlier would make this file's import order decide whether the
# package loads. There is no cycle to break (nothing under ``client`` imports
# ``live``), and importing it here rather than lazily keeps ``__all__`` honest:
# a name in ``__all__`` that only appears after a deferred import is a name
# ``dir()`` and static checkers cannot see.
#
# ``build_config_from_env`` is the ONLY thing exported from this module.
# ``read_credentials_from_env`` and ``live_enabled`` stay unexported: the first
# reads ``KORAIL_MEMBER_NO``/``KORAIL_PASSWORD``, and exporting it would make
# this package assert an opinion about where a caller's credentials live,
# which it deliberately does not have; the other is this repository's own
# smoke scaffolding, gated on an env flag, and is not an API anyone else has
# a reason to call. Configuration is a user's problem; credentials and smoke
# runs are ours.
from .live import build_config_from_env
from .models import (
    AppDataResponse,
    AppVersionInfo,
    BaseKorailResponse,
    KorailSession,
    KorailStation,
    MaasMenuItem,
    MaasMenuListResponse,
    NoticeResponse,
    PhysicalSeat,
    SeatAttribute,
    SeatCar,
    SeatCarListResponse,
    SeatInventoryResponse,
    SeatWindow,
    StationDataResponse,
    StationInfoResponse,
    TrainCalendarDay,
    TrainCalendarResponse,
    TrainScheduleResponse,
    TrainScheduleStop,
    TrainSearchContinuation,
    TrainSearchMetadata,
    TrainSearchQuery,
    TrainSearchResult,
    TrainSummary,
    TransferItinerary,
    TransferSearchResult,
    TransferStation,
    TransferStationListResponse,
    UuidResponse,
)
from .mutation_models import (
    CardPayment,
    CartAddRequest,
    DiscountCardAdditionalUser,
    DiscountCardPurchaseRequest,
    DiscountCardPurchaseResponse,
    DiscountCardSectionRequest,
    DiscountCardTicket,
    KorailPassengerCounts,
    KorailSeatAssignment,
    PaidTicket,
    PriceRecalculationRequest,
    PriceRecalculationRow,
    RefundTicketResponse,
    ReservationHoldResponse,
    ReservationJourney,
    ReservationPaymentCoupon,
    ReservationPaymentResponse,
    StationRefundExecutionRequest,
    StationRefundExecutionResponse,
    StationRefundOriginalTicket,
    StationRefundVerificationRequest,
    StationRefundVerificationResponse,
)
from .netfunnel import (
    KorailNetFunnelClient,
    KorailNetFunnelToken,
    inquiry_action,
)
from .read_models import (
    CartItem,
    CartListResponse,
    CommuterInfoResponse,
    CommuterKindMenuResponse,
    CommuterPassengerOption,
    CrewRequestListResponse,
    CrewRequestOption,
    CustomerTripInfo,
    CustomerTripInfoResponse,
    DelayDiscountTicket,
    DelayDiscountTicketListResponse,
    DeliveryRecipientResponse,
    DepositBank,
    DepositBankListResponse,
    DiscountCardOnTicket,
    DiscountCardScheduleResponse,
    DiscountCardScheduleTrain,
    DiscountCardSection,
    DiscountCardUsage,
    DiscountCardUsageListResponse,
    DiscountCoupon,
    DiscountCouponListResponse,
    FreeSeatCarResponse,
    GuideSeatConditionResponse,
    IntermediateStation,
    KorailPointSummaryResponse,
    MaasServiceDetail,
    MaasServiceDetailInfo,
    MaasServiceDetailListResponse,
    MergeSeatsInquiryResponse,
    MileageHistoryEntry,
    MileageHistoryResponse,
    MultiChildDiscountTarget,
    MultiChildDiscountTargetResponse,
    OriginalTicket,
    OriginalTicketInquiryResponse,
    OriginalTicketJourney,
    OriginalTicketSeat,
    PassAgeOption,
    PassAvailabilityMainInfo,
    PassAvailabilityResponse,
    PassGoodsInfo,
    PassMenuData,
    PassMenuItem,
    PassMenuResponse,
    PassOffice,
    PassOpenDate,
    PassPassengerInfo,
    PassPassengerInfos,
    PassPeriodOption,
    PassScheduleInfo,
    PassScheduleMainInfo,
    PassScheduleResponse,
    PassScheduleTrain,
    PbpAcceptanceJourney,
    PbpAcceptanceSeat,
    PbpAcceptanceSpecificationResponse,
    PbpAcceptanceTicket,
    PriceFare,
    PriceFareQuoteResponse,
    ProductDetailResponse,
    ProductReservation,
    ProductReservationListResponse,
    ReceiptCashPayment,
    ReceiptPayment,
    RecentDeliveryHistoryResponse,
    RecentDeliveryRecipient,
    RefundCommissionResponse,
    RefundTicketDetailResponse,
    RefundTicketJourney,
    RefundTicketSeat,
    ReservationDetailJourney,
    ReservationHistoryJourney,
    ReservationHistoryOriginalTicket,
    ReservationHistoryPassenger,
    ReservationHistoryReservation,
    ReservationHistoryResponse,
    ReservationHistoryTicket,
    ReservationHistoryTrain,
    ReservationSeatDetail,
    SeatAssignmentScheduleResponse,
    SelfSeatChangeInfoResponse,
    SelfSeatChangeReason,
    SelfSeatChangeStation,
    ServiceStatusResponse,
    TicketDuplicationCheckResponse,
    TicketListReservation,
    TicketListResponse,
    TicketListTicket,
    TicketReceipt,
    TicketReceiptResponse,
    TicketReservationDetailResponse,
    TrainScheduleItem,
    TripChangeDateResponse,
    TripMenuContent,
    TripMenuItem,
    TripMenuResponse,
)
from .read_payloads import (
    KORAIL_MILEAGE_LEDGER_KTX,
    KORAIL_MILEAGE_LEDGER_RAIL_POINT,
    KORAIL_MILEAGE_MOVEMENT_ALL,
    KORAIL_MILEAGE_MOVEMENT_EARNED,
    KORAIL_MILEAGE_MOVEMENT_SPENT,
    SELF_SEAT_CHANGE_ROOM_CLASS_CODES,
    CommuterInfoRequest,
    CommuterInitialRequest,
    CommuterPassengerRequest,
    CommuterTicketInquiryRequest,
    DiscountCardScheduleRequest,
    FreeSeatCarRequest,
    GuideSeatConditionRequest,
    KorailMileageLedger,
    KorailMileageMovement,
    KorailSelfSeatChangeRoomClassCode,
    MaasServiceDetailQuery,
    MergeSeatsInquiryRequest,
    MileageHistoryRequest,
    OriginalTicketReference,
    PassScheduleRequest,
    PriceFareLeg,
    PriceFareQuoteRequest,
    RefundCompanion,
    SeatAssignmentScheduleRequest,
    SelfSeatChangeInfoRequest,
    TicketDuplicationCheckRequest,
    TicketReservationDetailRequest,
)

# 마스킹 헬퍼. 이 패키지의 docstring 들이 호출자에게 **직접 쓰라고 지시하는**
# 함수들이라 공개면에 있어야 한다 — ``read_parsers`` 의
# :class:`~korail_mobile_api.read_models.OriginalTicket` 문서가 "로깅 또는 외부
# 직렬화 전에 ``redact_mapping`` 을 적용해야 합니다" 라고 적는다. 그런데 이
# 모듈 docstring 은 "``__all__`` 에
# 없는 것은 예고 없이 바뀝니다" 라고 선언한다 — 둘을 함께 두면 문서가 권하는
# 사용법이 비공개 API 에 기대게 된다. 여섯 개를 한 벌로 내보내는 것은 서로
# 맞물려 있기 때문이다: ``redact_value`` 는 문자열에 ``redact_url`` 을,
# ``redact_url`` 은 ``redact_text`` 를 쓰고, ``is_sensitive_key`` 는 셋 모두가
# 묻는 술어다. 일부만 내보내면 호출자가 나머지를 다시 비공개 경로에서 꺼내 쓴다.
#
# ``SENSITIVE_KEYS`` 자체는 일부러 빼 둔다. 어느 철자가 등록돼 있는가는 이
# 패키지의 내부 사정이고, 호출자가 물어야 할 것은 :func:`is_sensitive_key` 다.
from .redaction import (
    is_sensitive_key,
    redact_mapping,
    redact_payload,
    redact_text,
    redact_url,
    redact_value,
)


__all__ = [
    "AppDataResponse",
    "AppVersionInfo",
    "BaseKorailResponse",
    "CartAddRequest",
    "CartItem",
    "CartListResponse",
    "CommuterKindMenuResponse",
    "CommuterInfoRequest",
    "CommuterInfoResponse",
    "CommuterInitialRequest",
    "CommuterPassengerOption",
    "CommuterPassengerRequest",
    "CommuterTicketInquiryRequest",
    "CrewRequestListResponse",
    "CrewRequestOption",
    "CustomerTripInfo",
    "CustomerTripInfoResponse",
    "DynapathConfig",
    "DynapathTokenSettings",
    "DelayDiscountTicket",
    "DelayDiscountTicketListResponse",
    "DeliveryRecipientResponse",
    "DepositBank",
    "DepositBankListResponse",
    "DiscountCardScheduleRequest",
    "DiscountCardAdditionalUser",
    "DiscountCardOnTicket",
    "DiscountCardPurchaseRequest",
    "DiscountCardPurchaseResponse",
    "DiscountCardScheduleResponse",
    "DiscountCardScheduleTrain",
    "DiscountCardSection",
    "DiscountCardSectionRequest",
    "DiscountCardTicket",
    "DiscountCardUsage",
    "DiscountCardUsageListResponse",
    "DiscountCoupon",
    "DiscountCouponListResponse",
    "FreeSeatCarRequest",
    "FreeSeatCarResponse",
    "GuideSeatConditionRequest",
    "GuideSeatConditionResponse",
    "IntermediateStation",
    "KORAIL_COMMON_CODE_BOOTSTRAP_CODES",
    "KORAIL_DIRECT_ITINERARY_CODE",
    "KORAIL_MAX_DISCOUNT_CARD_SECTIONS",
    "KORAIL_MAX_JOURNEY_LEGS",
    "KORAIL_MAX_PASSENGERS_PER_RESERVATION",
    "KORAIL_MERGE_SEAT_FLAGS_BY_CABIN",
    "KORAIL_STANDBY_HOLD_MESSAGE_CODE",
    "KORAIL_TRANSFER_ITINERARY_CODE",
    "KORAIL_USER_AGENT",
    "KorailApiError",
    "KorailAppError",
    "KorailAppUpdateRequiredError",
    "KorailAuthContinuationRequired",
    "KorailAuthError",
    "KorailClient",
    "KorailConfig",
    "enabled_dynapath_config",
    "KorailDynaPathError",
    "KorailDynaPathRequiredError",
    "KorailInvalidRequestError",
    "KorailMutationNotAllowedError",
    "KorailNetFunnelAction",
    "KorailNetFunnelClient",
    "KorailNetFunnelError",
    "KorailNetFunnelToken",
    "KorailNoDirectTrainError",
    "KorailNoResultsError",
    "KorailNotEntitledError",
    "KorailPassengerCounts",
    "KorailQueueRejectedError",
    "KorailReservationJobType",
    "KorailReservationRefusedError",
    "KorailProtocolError",
    "KorailSeatAssignment",
    "KorailSeatClass",
    "KorailSeatUnavailableError",
    "KorailServiceUnavailableError",
    "KorailStation",
    "KorailSession",
    "KorailSessionExpiredError",
    "KorailSoldOutError",
    "KorailTransportError",
    "LimousineRecommendedProduct",
    "LimousineSchedule",
    "LimousineScheduleQuery",
    "LimousineScheduleResponse",
    "LimousineScheduleViewResponse",
    "LimousineScheduleViewTrain",
    "LimousineSeat",
    "LimousineSeatInventoryQuery",
    "LimousineSeatInventoryResponse",
    "MaasMenuItem",
    "MaasMenuListResponse",
    "MaasServiceDetail",
    "MaasServiceDetailInfo",
    "MaasServiceDetailListResponse",
    "MaasServiceDetailQuery",
    "MergeSeatsInquiryRequest",
    "MergeSeatsInquiryResponse",
    "KORAIL_MILEAGE_LEDGER_KTX",
    "KORAIL_MILEAGE_LEDGER_RAIL_POINT",
    "KORAIL_MILEAGE_MOVEMENT_ALL",
    "KORAIL_MILEAGE_MOVEMENT_EARNED",
    "KORAIL_MILEAGE_MOVEMENT_SPENT",
    "KorailMileageLedger",
    "KorailMileageMovement",
    "KorailPointSummaryResponse",
    "KorailSelfSeatChangeRoomClassCode",
    "MileageHistoryEntry",
    "MileageHistoryRequest",
    "MileageHistoryResponse",
    "MultiChildDiscountTarget",
    "MultiChildDiscountTargetResponse",
    "NoticeResponse",
    "OriginalTicket",
    "OriginalTicketInquiryResponse",
    "OriginalTicketJourney",
    "OriginalTicketReference",
    "OriginalTicketSeat",
    "PhysicalSeat",
    "PassAvailabilityMainInfo",
    "PassAvailabilityResponse",
    "PassAgeOption",
    "PassGoodsInfo",
    "PassMenuData",
    "PassMenuItem",
    "PassMenuResponse",
    "PassScheduleInfo",
    "PassScheduleMainInfo",
    "PassScheduleRequest",
    "PassScheduleResponse",
    "PassScheduleTrain",
    "PassOffice",
    "PassOpenDate",
    "PassPassengerInfo",
    "PassPassengerInfos",
    "PassPeriodOption",
    "PbpAcceptanceJourney",
    "PbpAcceptanceSeat",
    "PbpAcceptanceSpecificationResponse",
    "PbpAcceptanceTicket",
    "ProductDetailResponse",
    "ProductReservation",
    "ProductReservationListResponse",
    "PriceFare",
    "PriceFareLeg",
    "PriceFareQuoteRequest",
    "PriceFareQuoteResponse",
    "RecentDeliveryHistoryResponse",
    "RecentDeliveryRecipient",
    "ReceiptCashPayment",
    "ReceiptPayment",
    "RefundCommissionResponse",
    "RefundCompanion",
    "RefundTicketDetailResponse",
    "RefundTicketJourney",
    "RefundTicketSeat",
    "RefundTicketResponse",
    "StationRefundExecutionRequest",
    "StationRefundExecutionResponse",
    "StationRefundOriginalTicket",
    "StationRefundVerificationRequest",
    "StationRefundVerificationResponse",
    "ReservationDetailJourney",
    "ReservationHistoryJourney",
    "ReservationHistoryOriginalTicket",
    "ReservationHistoryPassenger",
    "ReservationHistoryReservation",
    "ReservationHistoryResponse",
    "ReservationHistoryTicket",
    "ReservationHistoryTrain",
    "ReservationSeatDetail",
    "CardPayment",
    "PaidTicket",
    "PriceRecalculationRequest",
    "PriceRecalculationRow",
    "ReservationHoldResponse",
    "ReservationJourney",
    "ReservationPaymentCoupon",
    "ReservationPaymentResponse",
    "SeatAttribute",
    "SeatCar",
    "SeatCarListResponse",
    "SeatInventoryResponse",
    "SeatAssignmentScheduleRequest",
    "SeatAssignmentScheduleResponse",
    "SeatWindow",
    "SELF_SEAT_CHANGE_ROOM_CLASS_CODES",
    "SelfSeatChangeInfoRequest",
    "SelfSeatChangeInfoResponse",
    "SelfSeatChangeReason",
    "SelfSeatChangeStation",
    "ServiceStatusResponse",
    "build_config_from_env",
    "inquiry_action",
    "StationDataResponse",
    "StationInfoResponse",
    "TrainCalendarDay",
    "TrainCalendarResponse",
    "TrainSearchContinuation",
    "TrainSearchQuery",
    "TrainSearchMetadata",
    "TrainSearchResult",
    "TrainScheduleResponse",
    "TrainScheduleStop",
    "TrainScheduleItem",
    "TrainSummary",
    "TransferItinerary",
    "TransferSearchResult",
    "TicketReceipt",
    "TicketReceiptResponse",
    "TicketReservationDetailRequest",
    "TicketReservationDetailResponse",
    "TicketDuplicationCheckRequest",
    "TicketDuplicationCheckResponse",
    "TicketListReservation",
    "TicketListResponse",
    "TicketListTicket",
    "TripMenuContent",
    "TripMenuItem",
    "TripMenuResponse",
    "TripChangeDateResponse",
    "TransferStation",
    "TransferStationListResponse",
    "UuidResponse",
    "classify_app_error",
    # redaction — 위 import 블록과 같은 묶음, 같은 순서.
    "is_sensitive_key",
    "redact_mapping",
    "redact_payload",
    "redact_text",
    "redact_url",
    "redact_value",
]
