"""KORAIL 모바일 앱 API 파이썬 클라이언트의 공개면.

여기서 import 할 수 있는 이름이 이 패키지가 지원하는 전부입니다. ``__all__`` 에
없는 것은 하위 모듈에 있더라도 예고 없이 바뀝니다.

시작점은 셋입니다 — :class:`~korail_mobile_api.client.KorailClient`(모든 호출),
:class:`~korail_mobile_api.config.KorailConfig`(기기 신원과 타임아웃),
:class:`~korail_mobile_api.consent.MutationConsent`(상태를 바꾸는 호출을 여는
열쇠). 대기열은 :class:`~korail_mobile_api.netfunnel.KorailNetFunnelClient` 로
따로 떨어져 있고 기본적으로 꺼져 있습니다.

실패는 :class:`~korail_mobile_api.errors.KorailApiError` 아래로 모이며,
``h_msg_cd`` 를 예외 클래스로 옮기는 규칙은
:func:`~korail_mobile_api.errors.classify_app_error` 하나에 있습니다.
"""

#: 배포된 버전. ``__all__`` 에 넣지 않는 것은 의도다 — 던더는 export 하는 이름
#: 집합이 아니고, ``from korail_mobile_api import *`` 가 이것을 실어 나른 적이
#: 없다. ``pyproject.toml`` 의 ``project.version`` 과 같은지는
#: ``tests/test_release_readiness.py`` 만 지킨다. 빌드가 둘을 맞춰 주지 않는다.
__version__ = "1.1.1"

from .client import KorailClient
from .config import KorailConfig, enabled_dynapath_config
from .consent import (
    MutationCategory,
    MutationConsent,
    MutationPreview,
    require_mutation_consent,
)
from .constants import (
    KORAIL_DIRECT_ITINERARY_CODE,
    KORAIL_MAX_DISCOUNT_CARD_SECTIONS,
    KORAIL_MAX_JOURNEY_LEGS,
    KORAIL_MAX_PASSENGERS_PER_RESERVATION,
    KORAIL_MERGE_SEAT_FLAGS_BY_CABIN,
    KORAIL_STANDBY_HOLD_MESSAGE_CODE,
    KORAIL_TRANSFER_ITINERARY_CODE,
    KORAIL_USER_AGENT,
    KorailNetFunnelAction,
    KorailReservationJobType,
    KorailSeatClass,
)
from .dynapath import (
    DynapathConfig,
    DynapathTokenSettings,
)
from .errors import (
    KorailApiError,
    KorailAppError,
    KorailAppUpdateRequiredError,
    KorailAuthContinuationRequired,
    KorailAuthError,
    KorailDynaPathError,
    KorailDynaPathRequiredError,
    KorailInvalidRequestError,
    KorailMutationNotAllowedError,
    KorailNetFunnelError,
    KorailNoDirectTrainError,
    KorailNoResultsError,
    KorailNotEntitledError,
    KorailProtocolError,
    KorailQueueRejectedError,
    KorailReservationRefusedError,
    KorailSeatUnavailableError,
    KorailServiceUnavailableError,
    KorailSessionExpiredError,
    KorailSoldOutError,
    KorailTransportError,
    classify_app_error,
)
from .limousine_models import (
    LimousineRecommendedProduct,
    LimousineSchedule,
    LimousineScheduleQuery,
    LimousineScheduleResponse,
    LimousineScheduleViewQuery,
    LimousineScheduleViewResponse,
    LimousineScheduleViewTrain,
    LimousineSeat,
    LimousineSeatInventoryQuery,
    LimousineSeatInventoryResponse,
)

# Imported LAST among the package's own modules on purpose. ``live`` sits on
# top of the stack — it imports ``client``, which imports everything else — so
# pulling it in earlier would make this file's import order decide whether the
# package loads. There is no cycle to break (nothing under ``client`` imports
# ``live``), and importing it here rather than lazily keeps ``__all__`` honest:
# a name in ``__all__`` that only appears after a deferred import is a name
# ``dir()`` and static checkers cannot see.
#
# ``build_config_from_env`` is the ONLY thing exported from this module.
# ``read_credentials_from_env``, ``live_enabled`` and ``run_live_smoke_from_env``
# stay unexported: the first reads ``KORAIL_MEMBER_NO``/``KORAIL_PASSWORD``, and
# exporting it would make this package assert an opinion about where a caller's
# credentials live, which it deliberately does not have; the other two are this
# repository's own smoke scaffolding, gated on an env flag, and are not an API
# anyone else has a reason to call. Configuration is a user's problem;
# credentials and smoke runs are ours.
from .live import build_config_from_env
from .models import (
    AppDataResponse,
    AppVersionInfo,
    BaseKorailResponse,
    KorailSession,
    KorailStation,
    MaasMenuItem,
    MaasMenuListResponse,
    NoticeResponse,
    PhysicalSeat,
    SeatAttribute,
    SeatCar,
    SeatCarListResponse,
    SeatInventoryResponse,
    SeatWindow,
    StationDataResponse,
    StationInfoResponse,
    TrainCalendarDay,
    TrainCalendarResponse,
    TrainScheduleResponse,
    TrainScheduleStop,
    TrainSearchContinuation,
    TrainSearchMetadata,
    TrainSearchQuery,
    TrainSearchResult,
    TrainSummary,
    TransferItinerary,
    TransferSearchResult,
    TransferStation,
    TransferStationListResponse,
    UuidResponse,
)
from .mutation_models import (
    CardPayment,
    CartAddRequest,
    DiscountCardAdditionalUser,
    DiscountCardPurchaseRequest,
    DiscountCardPurchaseResponse,
    DiscountCardSectionRequest,
    DiscountCardTicket,
    KorailPassengerCounts,
    KorailSeatAssignment,
    PaidTicket,
    PriceRecalculationRequest,
    PriceRecalculationRow,
    ReservationHoldResponse,
    ReservationJourney,
    ReservationPaymentCoupon,
    ReservationPaymentResponse,
)
from .netfunnel import (
    KorailNetFunnelClient,
    KorailNetFunnelToken,
    inquiry_action,
)
from .read_models import (
    CartItem,
    CartListResponse,
    CommuterInfoResponse,
    CommuterKindMenuResponse,
    CommuterPassengerOption,
    CrewRequestListResponse,
    CrewRequestOption,
    CustomerTripInfo,
    CustomerTripInfoResponse,
    DelayDiscountTicket,
    DelayDiscountTicketListResponse,
    DeliveryRecipientResponse,
    DepositBank,
    DepositBankListResponse,
    DiscountCardOnTicket,
    DiscountCardScheduleResponse,
    DiscountCardScheduleTrain,
    DiscountCardSection,
    DiscountCardUsage,
    DiscountCardUsageListResponse,
    DiscountCoupon,
    DiscountCouponListResponse,
    FreeSeatCarResponse,
    GiftTicket,
    GiftTicketListResponse,
    GuideSeatConditionResponse,
    IntermediateStation,
    KorailPointSummaryResponse,
    MaasServiceDetail,
    MaasServiceDetailListResponse,
    MergeSeatsInquiryResponse,
    MileageHistoryEntry,
    MileageHistoryResponse,
    MultiChildDiscountTarget,
    MultiChildDiscountTargetResponse,
    OriginalTicket,
    OriginalTicketInquiryResponse,
    OriginalTicketJourney,
    OriginalTicketSeat,
    PassAgeOption,
    PassAvailabilityResponse,
    PassGoodsInfo,
    PassMenuData,
    PassMenuItem,
    PassMenuResponse,
    PassOffice,
    PassPassengerInfo,
    PassPassengerInfos,
    PassPeriodOption,
    PassScheduleInfo,
    PassScheduleResponse,
    PassScheduleTrain,
    PbpAcceptanceJourney,
    PbpAcceptanceSeat,
    PbpAcceptanceSpecificationResponse,
    PbpAcceptanceTicket,
    PlatformNumberJourney,
    PlatformNumberResponse,
    PlatformNumberTicket,
    PriceFare,
    PriceFareQuoteResponse,
    ProductDetailResponse,
    ProductReservation,
    ProductReservationListResponse,
    ReceiptCashPayment,
    ReceiptPayment,
    RecentDeliveryHistoryResponse,
    RecentDeliveryRecipient,
    RefundCommissionResponse,
    RefundTicketDetailResponse,
    RefundTicketJourney,
    RefundTicketSeat,
    ReservationDetailJourney,
    ReservationHistoryResponse,
    ReservationHistoryTrain,
    ReservationSeatDetail,
    SeatAssignmentScheduleResponse,
    SelfSeatChangeInfoResponse,
    SelfSeatChangeReason,
    SelfSeatChangeStation,
    ServiceStatusResponse,
    TicketDuplicationCheckResponse,
    TicketReceipt,
    TicketReceiptResponse,
    TicketReservationDetailResponse,
    TrainScheduleItem,
    TripChangeDateResponse,
    TripMenuContent,
    TripMenuItem,
    TripMenuResponse,
)
from .read_payloads import (
    KORAIL_MILEAGE_LEDGER_KTX,
    KORAIL_MILEAGE_LEDGER_RAIL_POINT,
    KORAIL_MILEAGE_MOVEMENT_ALL,
    KORAIL_MILEAGE_MOVEMENT_EARNED,
    KORAIL_MILEAGE_MOVEMENT_SPENT,
    SELF_SEAT_CHANGE_ROOM_CLASS_CODES,
    CommuterInfoRequest,
    CommuterInitialRequest,
    CommuterPassengerRequest,
    CommuterTicketInquiryRequest,
    DiscountCardScheduleRequest,
    FreeSeatCarRequest,
    GiftTicketHistoryRequest,
    GiftTicketPaymentEligibilityRequest,
    GuideSeatConditionRequest,
    KorailMileageLedger,
    KorailMileageMovement,
    KorailSelfSeatChangeRoomClassCode,
    MaasServiceDetailQuery,
    MergeSeatsInquiryRequest,
    MileageHistoryRequest,
    OriginalTicketReference,
    PassScheduleRequest,
    PriceFareLeg,
    PriceFareQuoteRequest,
    RefundCompanion,
    SeatAssignmentScheduleRequest,
    SelfSeatChangeInfoRequest,
    TicketDuplicationCheckRequest,
    TicketReservationDetailRequest,
)


__all__ = [
    "AppDataResponse",
    "AppVersionInfo",
    "BaseKorailResponse",
    "CartAddRequest",
    "CartItem",
    "CartListResponse",
    "CommuterKindMenuResponse",
    "CommuterInfoRequest",
    "CommuterInfoResponse",
    "CommuterInitialRequest",
    "CommuterPassengerOption",
    "CommuterPassengerRequest",
    "CommuterTicketInquiryRequest",
    "CrewRequestListResponse",
    "CrewRequestOption",
    "CustomerTripInfo",
    "CustomerTripInfoResponse",
    "DynapathConfig",
    "DynapathTokenSettings",
    "DelayDiscountTicket",
    "DelayDiscountTicketListResponse",
    "DeliveryRecipientResponse",
    "DepositBank",
    "DepositBankListResponse",
    "DiscountCardScheduleRequest",
    "DiscountCardAdditionalUser",
    "DiscountCardOnTicket",
    "DiscountCardPurchaseRequest",
    "DiscountCardPurchaseResponse",
    "DiscountCardScheduleResponse",
    "DiscountCardScheduleTrain",
    "DiscountCardSection",
    "DiscountCardSectionRequest",
    "DiscountCardTicket",
    "DiscountCardUsage",
    "DiscountCardUsageListResponse",
    "DiscountCoupon",
    "DiscountCouponListResponse",
    "FreeSeatCarRequest",
    "FreeSeatCarResponse",
    "GiftTicket",
    "GiftTicketHistoryRequest",
    "GiftTicketListResponse",
    "GiftTicketPaymentEligibilityRequest",
    "GuideSeatConditionRequest",
    "GuideSeatConditionResponse",
    "IntermediateStation",
    "KORAIL_DIRECT_ITINERARY_CODE",
    "KORAIL_MAX_DISCOUNT_CARD_SECTIONS",
    "KORAIL_MAX_JOURNEY_LEGS",
    "KORAIL_MAX_PASSENGERS_PER_RESERVATION",
    "KORAIL_MERGE_SEAT_FLAGS_BY_CABIN",
    "KORAIL_STANDBY_HOLD_MESSAGE_CODE",
    "KORAIL_TRANSFER_ITINERARY_CODE",
    "KORAIL_USER_AGENT",
    "KorailApiError",
    "KorailAppError",
    "KorailAppUpdateRequiredError",
    "KorailAuthContinuationRequired",
    "KorailAuthError",
    "KorailClient",
    "KorailConfig",
    "enabled_dynapath_config",
    "KorailDynaPathError",
    "KorailDynaPathRequiredError",
    "KorailInvalidRequestError",
    "KorailMutationNotAllowedError",
    "KorailNetFunnelAction",
    "KorailNetFunnelClient",
    "KorailNetFunnelError",
    "KorailNetFunnelToken",
    "KorailNoDirectTrainError",
    "KorailNoResultsError",
    "KorailNotEntitledError",
    "KorailPassengerCounts",
    "KorailQueueRejectedError",
    "KorailReservationJobType",
    "KorailReservationRefusedError",
    "KorailProtocolError",
    "KorailSeatAssignment",
    "KorailSeatClass",
    "KorailSeatUnavailableError",
    "KorailServiceUnavailableError",
    "KorailStation",
    "KorailSession",
    "KorailSessionExpiredError",
    "KorailSoldOutError",
    "KorailTransportError",
    "LimousineRecommendedProduct",
    "LimousineSchedule",
    "LimousineScheduleQuery",
    "LimousineScheduleResponse",
    "LimousineScheduleViewQuery",
    "LimousineScheduleViewResponse",
    "LimousineScheduleViewTrain",
    "LimousineSeat",
    "LimousineSeatInventoryQuery",
    "LimousineSeatInventoryResponse",
    "MaasMenuItem",
    "MaasMenuListResponse",
    "MaasServiceDetail",
    "MaasServiceDetailListResponse",
    "MaasServiceDetailQuery",
    "MergeSeatsInquiryRequest",
    "MergeSeatsInquiryResponse",
    "KORAIL_MILEAGE_LEDGER_KTX",
    "KORAIL_MILEAGE_LEDGER_RAIL_POINT",
    "KORAIL_MILEAGE_MOVEMENT_ALL",
    "KORAIL_MILEAGE_MOVEMENT_EARNED",
    "KORAIL_MILEAGE_MOVEMENT_SPENT",
    "KorailMileageLedger",
    "KorailMileageMovement",
    "KorailPointSummaryResponse",
    "KorailSelfSeatChangeRoomClassCode",
    "MileageHistoryEntry",
    "MileageHistoryRequest",
    "MileageHistoryResponse",
    "MultiChildDiscountTarget",
    "MultiChildDiscountTargetResponse",
    "MutationCategory",
    "MutationConsent",
    "MutationPreview",
    "NoticeResponse",
    "OriginalTicket",
    "OriginalTicketInquiryResponse",
    "OriginalTicketJourney",
    "OriginalTicketReference",
    "OriginalTicketSeat",
    "PhysicalSeat",
    "PassAvailabilityResponse",
    "PassAgeOption",
    "PassGoodsInfo",
    "PassMenuData",
    "PassMenuItem",
    "PassMenuResponse",
    "PassScheduleInfo",
    "PassScheduleRequest",
    "PassScheduleResponse",
    "PassScheduleTrain",
    "PassOffice",
    "PassPassengerInfo",
    "PassPassengerInfos",
    "PassPeriodOption",
    "PbpAcceptanceJourney",
    "PbpAcceptanceSeat",
    "PbpAcceptanceSpecificationResponse",
    "PbpAcceptanceTicket",
    "ProductDetailResponse",
    "ProductReservation",
    "ProductReservationListResponse",
    "PriceFare",
    "PriceFareLeg",
    "PriceFareQuoteRequest",
    "PriceFareQuoteResponse",
    "PlatformNumberJourney",
    "PlatformNumberResponse",
    "PlatformNumberTicket",
    "RecentDeliveryHistoryResponse",
    "RecentDeliveryRecipient",
    "ReceiptCashPayment",
    "ReceiptPayment",
    "RefundCommissionResponse",
    "RefundCompanion",
    "RefundTicketDetailResponse",
    "RefundTicketJourney",
    "RefundTicketSeat",
    "ReservationDetailJourney",
    "ReservationHistoryResponse",
    "ReservationHistoryTrain",
    "ReservationSeatDetail",
    "CardPayment",
    "PaidTicket",
    "PriceRecalculationRequest",
    "PriceRecalculationRow",
    "ReservationHoldResponse",
    "ReservationJourney",
    "ReservationPaymentCoupon",
    "ReservationPaymentResponse",
    "SeatAttribute",
    "SeatCar",
    "SeatCarListResponse",
    "SeatInventoryResponse",
    "SeatAssignmentScheduleRequest",
    "SeatAssignmentScheduleResponse",
    "SeatWindow",
    "SELF_SEAT_CHANGE_ROOM_CLASS_CODES",
    "SelfSeatChangeInfoRequest",
    "SelfSeatChangeInfoResponse",
    "SelfSeatChangeReason",
    "SelfSeatChangeStation",
    "ServiceStatusResponse",
    "build_config_from_env",
    "inquiry_action",
    "require_mutation_consent",
    "StationDataResponse",
    "StationInfoResponse",
    "TrainCalendarDay",
    "TrainCalendarResponse",
    "TrainSearchContinuation",
    "TrainSearchQuery",
    "TrainSearchMetadata",
    "TrainSearchResult",
    "TrainScheduleResponse",
    "TrainScheduleStop",
    "TrainScheduleItem",
    "TrainSummary",
    "TransferItinerary",
    "TransferSearchResult",
    "TicketReceipt",
    "TicketReceiptResponse",
    "TicketReservationDetailRequest",
    "TicketReservationDetailResponse",
    "TicketDuplicationCheckRequest",
    "TicketDuplicationCheckResponse",
    "TripMenuContent",
    "TripMenuItem",
    "TripMenuResponse",
    "TripChangeDateResponse",
    "TransferStation",
    "TransferStationListResponse",
    "UuidResponse",
    "classify_app_error",
]
